stages:          # List of stages for jobs, and their order of execution
  - build
  - test

before_script:
  - echo "Running global before_script"
  - git config --global credential.helper store
  - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lukevassallo.com" > ~/.git-credentials

after_script:
#  - source setup.sh
  - ./clean.sh

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - general-purpose, gpu-enabled
  before_script:
    - echo "Running local before script"
    - ./install_tools_and_virtual_environment.sh
  variables:
    GIT_STRATEGY: fetch
  script:
    - echo "Compiling the code..."
    - source setup.sh
    - echo ${RL_PCB}
    - ls -alh
    - echo "Compile complete."

system-test-gpu-td3:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  tags:
    - general-purpose, gpu-enabled
  variables:
    GIT_STRATEGY: fetch
  timeout: 12h 0m
  script:
    - ./install_tools_and_virtual_environment.sh
    - source setup.sh
    - echo ${RL_PCB}
    - cd ${RL_PCB}/tests/05_training_td3_cuda_fast/
    - ./run.sh
  artifacts:
    paths:
      - ./tests/05_training_td3_cuda_fast/work/eval_testing_set/evaluation_report_mean.pdf
      - ./tests/05_training_td3_cuda_fast/experiment_report.pdf

system-test-gpu-sac:  # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  tags:
    - general-purpose, gpu-enabled
  variables:
    GIT_STRATEGY: fetch
  timeout: 12h 0m
  script:
    - ./install_tools_and_virtual_environment.sh
    - source setup.sh
    - echo ${RL_PCB}
    - cd ${RL_PCB}/tests/07_training_sac_cuda_fast/
    - ./run.sh
  artifacts:
    paths:
      - ./tests/07_training_sac_cuda_fast/work/eval_testing_set/evaluation_report_mean.pdf
      - ./tests/07_training_sac_cuda_fast/experiment_report.pdf      

system-test-cpu:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  tags:
    - general-purpose, gpu-enabled
  variables:
    GIT_STRATEGY: fetch
  timeout: 12h 0m
  script:
    - ./install_tools_and_virtual_environment.sh --cpu_only
    - source setup.sh
    - echo ${RL_PCB}
    - cd ${RL_PCB}/tests/06_training_td3_cpu_fast/
    - ./run.sh
  artifacts:
    paths:
      - ./tests/06_training_td3_cpu_fast/work/eval_testing_set/evaluation_report_mean.pdf
      - ./tests/06_training_td3_cpu_fast/experiment_report.pdf
