pipeline {
    agent any

    stages {
        stage("library") {
            steps {
                echo "Building the library"
                sh 'make library'
            }
        }

        stage("application") {
            steps {
                echo "Building the application"
                sh 'make test_app'
            }
        }

        stage("test") {
            steps {
                echo "Testing the application"
                sh 'make run_test_app'
            }
        }
    }
    post {
        always {
            echo "Always"
        }
        success {
            echo "Success"
        }
        failure {
            echo "Failure"
        }
    }
}
